# Export Engine — PDF and DOCX generation from markdown reports
import io
import re
import logging
from pathlib import Path

logger = logging.getLogger(__name__)


def markdown_to_html(markdown_text: str) -> str:
    """Convert markdown to styled HTML for PDF export."""
    try:
        import markdown
        html_body = markdown.markdown(
            markdown_text,
            extensions=['tables', 'fenced_code', 'codehilite', 'toc', 'nl2br']
        )
    except ImportError:
        # Fallback: basic conversion
        html_body = markdown_text.replace('\n', '<br/>')

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');
    
    * {{ margin: 0; padding: 0; box-sizing: border-box; }}
    
    body {{
        font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
        font-size: 11pt;
        line-height: 1.8;
        color: #1a1a2e;
        max-width: 800px;
        margin: 0 auto;
        padding: 60px 40px;
    }}
    
    h1 {{
        font-size: 28pt;
        font-weight: 700;
        color: #0f0f23;
        margin: 40px 0 20px;
        padding-bottom: 12px;
        border-bottom: 3px solid #3b82f6;
        letter-spacing: -0.5px;
    }}
    
    h2 {{
        font-size: 20pt;
        font-weight: 600;
        color: #16213e;
        margin: 32px 0 16px;
        padding-bottom: 8px;
        border-bottom: 1px solid #e2e8f0;
    }}
    
    h3 {{
        font-size: 14pt;
        font-weight: 600;
        color: #1e3a5f;
        margin: 24px 0 12px;
    }}
    
    p {{ margin: 12px 0; }}
    
    a {{
        color: #3b82f6;
        text-decoration: none;
        font-weight: 500;
    }}
    
    blockquote {{
        border-left: 4px solid #3b82f6;
        background: #f8fafc;
        padding: 16px 20px;
        margin: 20px 0;
        font-style: italic;
        color: #475569;
        border-radius: 0 8px 8px 0;
    }}
    
    table {{
        width: 100%;
        border-collapse: collapse;
        margin: 20px 0;
        font-size: 10pt;
    }}
    
    th {{
        background: #1e293b;
        color: white;
        padding: 12px 16px;
        text-align: left;
        font-weight: 600;
    }}
    
    td {{
        padding: 10px 16px;
        border-bottom: 1px solid #e2e8f0;
    }}
    
    tr:nth-child(even) td {{ background: #f8fafc; }}
    
    code {{
        background: #f1f5f9;
        padding: 2px 6px;
        border-radius: 4px;
        font-family: 'JetBrains Mono', monospace;
        font-size: 9pt;
    }}
    
    pre {{
        background: #1e293b;
        color: #e2e8f0;
        padding: 20px;
        border-radius: 8px;
        overflow-x: auto;
        margin: 16px 0;
    }}
    
    pre code {{
        background: transparent;
        color: inherit;
    }}
    
    ul, ol {{ padding-left: 24px; margin: 12px 0; }}
    li {{ margin: 6px 0; }}
    
    .report-header {{
        text-align: center;
        margin-bottom: 40px;
        padding-bottom: 24px;
        border-bottom: 2px solid #e2e8f0;
    }}
    
    .report-header .badge {{
        display: inline-block;
        background: #3b82f6;
        color: white;
        padding: 4px 12px;
        border-radius: 20px;
        font-size: 8pt;
        font-weight: 700;
        letter-spacing: 1px;
        text-transform: uppercase;
        margin-bottom: 12px;
    }}
    
    .report-footer {{
        margin-top: 60px;
        padding-top: 20px;
        border-top: 1px solid #e2e8f0;
        text-align: center;
        font-size: 8pt;
        color: #94a3b8;
    }}
</style>
</head>
<body>
    <div class="report-header">
        <div class="badge">Allmighty Deep Search Report</div>
    </div>
    {html_body}
    <div class="report-footer">
        Generated by Allmighty Deep Search Engine &bull; Powered by AI
    </div>
</body>
</html>"""


def export_to_pdf(markdown_text: str, title: str = "Research Report") -> bytes:
    """Export markdown report to PDF bytes."""
    html = markdown_to_html(markdown_text)
    
    try:
        from weasyprint import HTML
        pdf_bytes = HTML(string=html).write_pdf()
        logger.info(f"PDF exported successfully: {title}")
        return pdf_bytes
    except ImportError:
        logger.warning("WeasyPrint not installed. Using fallback HTML-to-PDF.")
        # Fallback: return HTML as bytes (can be opened in browser and printed)
        return html.encode('utf-8')


def export_to_html(markdown_text: str, title: str = "Research Report") -> bytes:
    """Export markdown report to styled HTML bytes."""
    html = markdown_to_html(markdown_text)
    return html.encode('utf-8')


def export_to_txt(markdown_text: str, title: str = "Research Report") -> bytes:
    """Export markdown report to plain text bytes."""
    # Remove simple markdown tags if needed, but usually TXT researchers want the clean MD or strip MD.
    # We'll provide clean MD as it's the standard for text-based reports.
    return markdown_text.encode('utf-8')


def export_to_docx(markdown_text: str, title: str = "Research Report") -> bytes:
    """Export markdown report to DOCX bytes."""
    try:
        from docx import Document
        from docx.shared import Inches, Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH
    except ImportError:
        logger.error("python-docx not installed")
        return b""
    
    doc = Document()
    
    # Set default font
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Calibri'
    font.size = Pt(11)
    
    # Add header
    header_para = doc.add_paragraph()
    header_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = header_para.add_run("ALLMIGHTY DEEP SEARCH REPORT")
    run.bold = True
    run.font.size = Pt(9)
    run.font.color.rgb = RGBColor(59, 130, 246)
    
    # Parse markdown into paragraphs
    lines = markdown_text.split('\n')
    
    for line in lines:
        stripped = line.strip()
        
        if not stripped:
            doc.add_paragraph("")
            continue
        
        # Headers
        if stripped.startswith('### '):
            heading = doc.add_heading(stripped[4:], level=3)
        elif stripped.startswith('## '):
            heading = doc.add_heading(stripped[3:], level=2)
        elif stripped.startswith('# '):
            heading = doc.add_heading(stripped[2:], level=1)
        
        # Bullet points
        elif stripped.startswith('- ') or stripped.startswith('* '):
            doc.add_paragraph(stripped[2:], style='List Bullet')
        elif re.match(r'^\d+\.', stripped):
            content = re.sub(r'^\d+\.\s*', '', stripped)
            doc.add_paragraph(content, style='List Number')
        
        # Blockquotes
        elif stripped.startswith('> '):
            para = doc.add_paragraph(stripped[2:])
            para.style = doc.styles['Normal']
            for run in para.runs:
                run.italic = True
                run.font.color.rgb = RGBColor(100, 116, 139)
        
        # Regular paragraph
        else:
            # Handle bold and italic
            para = doc.add_paragraph()
            parts = re.split(r'(\*\*.*?\*\*|\*.*?\*)', stripped)
            for part in parts:
                if part.startswith('**') and part.endswith('**'):
                    run = para.add_run(part[2:-2])
                    run.bold = True
                elif part.startswith('*') and part.endswith('*'):
                    run = para.add_run(part[1:-1])
                    run.italic = True
                else:
                    para.add_run(part)
    
    # Footer
    doc.add_paragraph("")
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = footer.add_run("Generated by Allmighty Deep Search Engine")
    run.font.size = Pt(8)
    run.font.color.rgb = RGBColor(148, 163, 184)
    
    # Save to bytes
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.read()
